using TradingStation.Contracts;

namespace TradingStation.Backtesting;

/// <summary>
/// Interface for trading strategies to be used in backtesting
/// </summary>
public interface ITradingStrategy
{
    /// <summary>
    /// Generates trading signals for the current date
    /// </summary>
    /// <param name="dataProvider">Temporal-safe market data provider</param>
    /// <param name="currentDate">Current simulation date</param>
    /// <returns>List of trading signals to execute</returns>
    Task<IEnumerable<TradingSignal>> GenerateSignalsAsync(
        IMarketDataProvider dataProvider,
        DateTime currentDate);
}

/// <summary>
/// Represents a trading signal generated by a strategy
/// </summary>
public class TradingSignal
{
    public string Symbol { get; set; } = string.Empty;
    public OrderType OrderType { get; set; }
    public int Quantity { get; set; }
    public StopLossConfig? StopLoss { get; set; }
    public string Reason { get; set; } = string.Empty;
}
